name: btblocklist

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    
    - name: initialize
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: remove binary files from history (reduce the repo size)
      run: |
        git filter-branch --force --index-filter "git rm --cached --ignore-unmatch bt_blocklists.gz" --prune-empty --tag-name-filter cat -- --all
        rm -rf .git/refs/original/
        git reflog expire --expire=now --all
        git gc --prune=now
        git gc --aggressive --prune=now
   
    - name: Run build script
      run: |
        chmod +x ./update.sh
        ./update.sh
      shell: bash
        
    - name: Push
      run: |
        git add .
        git commit -m "auto update"
        git push origin --force --all
        du -sh .git      
        
    
